apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-probe-payload-oi6f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-probe-payload-oi6f
    app.kubernetes.io/part-of: ralphtest
  name: hacbs-probe-payload-oi6f
  namespace: ralphjbean-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hacbs-probe-payload-oi6f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hacbs-probe-payload-oi6f
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:b6cd62b267238691ff068abd6148fb53c7ffaf74e022795284032255cd9706cd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
