apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-probe-payload-oi6f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-probe-payload-oi6f
    app.kubernetes.io/part-of: ralphtest
  name: hacbs-probe-payload-oi6f
  namespace: ralphjbean-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacbs-probe-payload-oi6f
    weight: 100
status: {}
