apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-probe-payload-oi6f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-probe-payload-oi6f
    app.kubernetes.io/part-of: ralphtest
  name: hacbs-probe-payload-oi6f
  namespace: ralphjbean-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: hacbs-probe-payload-oi6f
status:
  loadBalancer: {}
